title: Network Worms
description: We make software for PC not PCs for software
author: Vitaliy Levin
encoding: "UTF-8"
timezone: Europe/Moscow
permalink: pretty
highlighter: rogue
markdown: kramdown
repository: VitalikLevin/VitalikLevin.github.io
theme: null
url: https://vitaliklevin.github.io
port: 2804
license: https://creativecommons.org/licenses/by-sa/4.0/
license_ru: https://creativecommons.org/licenses/by-sa/4.0/deed.ru
og_p: "/files/images/spaceworm.png"
og_pa: "A pink worm in space"
status: "/files/svg/emoji/1f385.svg"
launch_time: "2022-01-28T07:54:37Z"
steamyfish: https://marketplace.visualstudio.com/items?itemName=networkworms.steamyfish
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "files"
    values:
      sw-include: true
      layout: null
  - scope:
      path: "files/fonts/*f"
    values:
      sw-include: false
  - scope:
      path: "files/images"
    values:
      sw-include: false
  - scope:
      path: "files/video"
    values:
      sw-include: false
  - scope:
      path: "files/xml"
    values:
      sw-include: false
  - scope:
      path: "favicon.ico"
    values:
      sw-include: true
  - scope:
      path: "index.html"
    values:
      sw-include: true
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.*
whitelist:
  - jekyll-redirect-from
redirect_from:
  json: false